name = "cbtrank"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "cbtrank_db"
database_id = "fd29c541-3fd2-4fa8-8dc1-19809ab907c3"

# Cloudflare R2 Object Storage Bucket Binding (for Images & Uploads)
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cbtrank-uploads"
